JoppeDc\SyliusBetterSeoPlugin\Entity\Seo:
    type: entity
    table: joppedc_seo
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
