JoppeDc\SyliusBetterSeoPlugin\Entity\Taxon:
    type: entity
    table: sylius_taxon
    oneToOne:
        seo:
            targetEntity: Seo
            joinColumn:
                name: seo_id
                referencedColumnName: id
            cascade: [ all ]
